url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Charlie Hammond"

defaults:
   - scope:
        path: ""
        type: "posts"
     values:
        layout: "post"
        author: "Charlie Hammond"

# Archives
collections:
   archives:
      output: true
      permalink: /archives/:path/
